version: '3'
services:
  app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    restart: always
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb+srv://yuliabarbashova:fTiOkB5mVjOlvJLb@cluster0.0k6us4d.mongodb.net/test
    depends_on:
      - mongo
    networks:
      - my_network
  mongo:
    container_name: mongo
    image:  mongo:latest
    restart: always
    volumes:
      - ./data/mongo:/data/db
    networks:
      - my_network